POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

//{"username": "test3@gmail.com", "password": "Passkey1234!"}
{"username": "1", "password": "1"}

###

###

POST http://127.0.0.1:8000/auth/signup/
Content-Type: application/json

{
  "username": "testuser5@gmail.com",
  "password": "1",
  "email": "testuser5@gmail.com",
  "first_name": "John",
  "last_name": "Doe",
  "pricingplanid": 1,
  "professionid": 3
}

###

GET http://127.0.0.1:8000/auth/validate_token/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

{}

###
#--------------------------- Component ----------------------------
#

POST http://127.0.0.1:8000/component/create_component/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

{
  "ComponentName": "My Component Name Test",
  "ComponentDescription": "Testdescription",
  "ComponentPPT": "AP8QIDBAUGBwaICQoLCw0ODw==",
  "ComponentPreview": "AP8QIDBAUGBwaICQoLCw0ODw==",
  "ComponentPublic": false,
  "ComponentHeight": "600",
  "ComponentWidth": "800"
}

###
GET http://127.0.0.1:8000/component/get_component_by_id/7
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/component/get_user_components_all/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/component/get_user_components_my_components/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/component/get_components_default/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/component/get_components_public/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/component/get_component_teams/14
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4


#---------------------------- TEAM --------------------------------------

###
GET http://127.0.0.1:8000/teams/get_user_teams_all/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/teams/get_user_teams_all_details/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
POST  http://127.0.0.1:8000/teams/create_new_team/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

{
  "teamname": "TestTeam"
}

###
GET http://127.0.0.1:8000/teams/get_users_in_team/5
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/teams/get_all_roles
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
POST http://127.0.0.1:8000/teams/add_components/team/5/component/14
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
DELETE  http://127.0.0.1:8000/teams/remove_components/team/5/component/15
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/teams/get_team_components/5
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

### 
POST http://localhost:8000/teams/add_user_to_team/5
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

{
  "user_id": 4
}

###
POST http://localhost:8000/teams/remove_user_from_team/5
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4
Content-Type: application/json

{
  "user_id": 11
}


#---------------------------- User --------------------------------------

###
GET http://127.0.0.1:8000/user/get_company_users/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

### Suche nach Nutzern, die NICHT in Team 3 sind, nach dem Stichwort "john"
GET http://127.0.0.1:8000/user/get_company_users_but_not_team/?search=john&team_id=5
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/user/get_user_components_favorites/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
POST http://127.0.0.1:8000/user/toggle_favorite/10
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
DELETE http://127.0.0.1:8000/user/toggle_favorite/10
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET  http://127.0.0.1:8000/teams/get_team_role/6/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4


#---------------------------- Company --------------------------------------

###
GET http://127.0.0.1:8000/company/roles/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/company/roles/1/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/company/user-role/3/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
GET http://127.0.0.1:8000/company/joinrequests/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
POST http://127.0.0.1:8000/company/joinrequests/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

{
  "company": 1
}

###
POST http://127.0.0.1:8000/company/joinrequests/12/approve/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

###
POST http://127.0.0.1:8000/company/joinrequests/12/reject/
Content-Type: application/json
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4

### Neue Firma registrieren
POST http://127.0.0.1:8000/company/create/
Content-Type: application/json
Authorization: Token e005d9821f098f477cfe6d02d17e37647d7fa959

{
  "companyname": "Company3"
}

###
GET http://127.0.0.1:8000/company/verify/05ef0651-b3b2-48d5-b0a7-a6963bbaf63e/
Content-Type: application/json
Authorization: Token e005d9821f098f477cfe6d02d17e37647d7fa959

# Token aus E-Mail extrahieren und hier einsetzen
# z. B. wenn die Mail folgendes enthält:
# https://api.slidecomponents.com/company/verify/6fb7e0c1-0a8d-43e9-9ad4-f8c9ef123abc/
# dann:
### Einladung senden (als Admin)
POST http://127.0.0.1:8000/onboarding/invite/send/
Authorization: Token 4b30bcb6edae8a36bdac95345351fa62c2e7b4c4
Content-Type: application/json

{
  "email": "neuer.mitarbeiter@example.com",
  "companyid": 1
}


### Einladung annehmen (als eingeladener User)
POST http://127.0.0.1:8000/onboarding/invite/accept/
Authorization: Token e005d9821f098f477cfe6d02d17e37647d7fa959
Content-Type: application/json

{
  "invite_token": "8d420036-4feb-44e6-a35f-a9fe48d4d8d7"
}


###
# Fall 1: Blockierte Domain (z. B. gmail.com)
GET http://127.0.0.1:8000/onboarding/check_user_onboarding_case/?email=testuser@gmail.com
Content-Type: application/json

###
# Fall 2: Einladung via Invite-Token (aus E-Mail-Link)
GET http://127.0.0.1:8000/onboarding/check_user_onboarding_case/?invite_token=c89060ee-8d43-4f89-ba9c-a3f2f605b62c
Content-Type: application/json

###
# Fall 3: Nutzer wurde per Mail eingeladen
GET http://127.0.0.1:8000/onboarding/check_user_onboarding_case/?email=neuer.mitarbeiter@example.com
Content-Type: application/json

###
# Fall 4: Nutzer-Mail gehört zu bekannter Firmendomain
GET http://127.0.0.1:8000/onboarding/check_user_onboarding_case/?email=max.mustermann@sub.example.com
Content-Type: application/json

###
# Fall 5: Neue Firma (unbekannte Domain)
GET http://127.0.0.1:8000/onboarding/check_user_onboarding_case/?email=gründer@neuefirma.ai
Content-Type: application/json

###
# Fehler: Ungültige oder fehlende E-Mail
GET http://127.0.0.1:8000/onboarding/check_user_onboarding_case/
Content-Type: application/json
