# Generated by Django 6.0 on 2026-01-02 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='community',
            name='communities_created_4d42e1_idx',
        ),
        migrations.AddField(
            model_name='community',
            name='external_display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='community',
            name='external_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='external_login',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='community',
            name='external_profile_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='platform',
            field=models.CharField(choices=[('twitch', 'Twitch')], default='twitch', max_length=32),
        ),
        migrations.AddField(
            model_name='community',
            name='status',
            field=models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed')], default='unclaimed', max_length=32),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['platform', 'external_id'], name='communities_platfor_0ee675_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['status'], name='communities_status_82971c_idx'),
        ),
        migrations.AddConstraint(
            model_name='community',
            constraint=models.UniqueConstraint(fields=('platform', 'external_id'), name='uniq_community_platform_external_id'),
        ),
    ]
