# Generated by Django 5.1.5 on 2025-02-05 11:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('companyname', models.TextField(db_column='CompanyName')),
                ('companymail', models.TextField(blank=True, db_column='CompanyMail', null=True)),
            ],
            options={
                'db_table': 'Company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('pricingplanid', models.AutoField(db_column='PricingPlanID', primary_key=True, serialize=False)),
                ('pricingplanname', models.TextField(db_column='PricingPlanName')),
                ('pricingplandescription', models.TextField(blank=True, db_column='PricingPlanDescription', null=True)),
                ('pricingplanmonthlypriceeur', models.FloatField(blank=True, db_column='PricingPlanMonthlyPriceEUR', null=True)),
            ],
            options={
                'db_table': 'PricingPlan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('professionid', models.IntegerField(blank=True, db_column='professionid', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('companyid', models.ForeignKey(blank=True, db_column='companyid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.company')),
                ('pricingplanid', models.ForeignKey(blank=True, db_column='pricingplanid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.pricingplan')),
            ],
            options={
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('componentid', models.AutoField(db_column='ComponentID', primary_key=True, serialize=False)),
                ('componentname', models.TextField(db_column='ComponentName')),
                ('componentdescription', models.TextField(blank=True, db_column='ComponentDescription', null=True)),
                ('componentppt', models.BinaryField(blank=True, db_column='ComponentPPT', null=True)),
                ('componentpreview', models.BinaryField(blank=True, db_column='ComponentPreview', null=True)),
                ('componentpublic', models.BooleanField(db_column='ComponentPublic', default=False)),
                ('componentwidth', models.DecimalField(blank=True, db_column='ComponentWidth', decimal_places=2, max_digits=10, null=True)),
                ('componentheight', models.DecimalField(blank=True, db_column='ComponentHeight', decimal_places=2, max_digits=10, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Component',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyComponents',
            fields=[
                ('companycomponentsid', models.AutoField(db_column='CompanyComponentsID', primary_key=True, serialize=False)),
                ('companyid', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='server.company')),
                ('componentid', models.ForeignKey(db_column='ComponentID', on_delete=django.db.models.deletion.CASCADE, to='server.component')),
            ],
            options={
                'db_table': 'CompanyComponents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(db_column='TeamID', primary_key=True, serialize=False)),
                ('teamname', models.TextField(db_column='TeamName')),
                ('companyid', models.ForeignKey(blank=True, db_column='CompanyID', null=True, on_delete=django.db.models.deletion.CASCADE, to='server.company')),
                ('creatoruserid', models.ForeignKey(blank=True, db_column='CreatorUserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Team',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamComponents',
            fields=[
                ('teamcomponentsid', models.AutoField(db_column='TeamComponentsID', primary_key=True, serialize=False)),
                ('componentid', models.ForeignKey(db_column='ComponentID', on_delete=django.db.models.deletion.CASCADE, to='server.component')),
                ('teamid', models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, to='server.team')),
            ],
            options={
                'db_table': 'TeamComponents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('teamuserid', models.AutoField(db_column='TeamUserID', primary_key=True, serialize=False)),
                ('teamroleofuser', models.TextField(blank=True, db_column='TeamRoleOfUser', null=True)),
                ('teamid', models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.CASCADE, to='server.team')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TeamUser',
                'managed': True,
            },
        ),
    ]
