# Generated by Django 5.1.5 on 2025-03-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('teamroleid', models.AutoField(db_column='TeamRoleID', primary_key=True, serialize=False)),
                ('rolename', models.TextField(db_column='RoleName', unique=True)),
                ('perm_add_people', models.BooleanField(db_column='PermAddPeople', default=False)),
                ('perm_remove_people', models.BooleanField(db_column='PermRemovePeople', default=False)),
                ('perm_change_role', models.BooleanField(db_column='PermChangeRole', default=False)),
                ('perm_remove_component', models.BooleanField(db_column='PermRemoveComponent', default=False)),
            ],
            options={
                'db_table': 'TeamRole',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='teamuser',
            name='teamroleofuser',
        ),
        migrations.AddField(
            model_name='teamuser',
            name='teamrole',
            field=models.ForeignKey(blank=True, db_column='TeamRoleID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.teamrole'),
        ),
    ]
