# Generated by Django 5.1.5 on 2025-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_teamrole_remove_teamuser_teamroleofuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='componentdefault',
            field=models.BooleanField(db_column='ComponentDefault', default=False),
        ),
    ]
