# Generated by Django 5.1.5 on 2025-05-04 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_component_componentdefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFavorite',
            fields=[
                ('componentfavoriteid', models.AutoField(db_column='ComponentFavoriteID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('componentid', models.ForeignKey(db_column='ComponentID', on_delete=django.db.models.deletion.CASCADE, to='server.component')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ComponentFavorite',
                'managed': True,
                'unique_together': {('userid', 'componentid')},
            },
        ),
    ]
