# Generated by Django 5.1.5 on 2025-05-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_componentfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Wird bei jedem Speichern auf die aktuelle Zeit gesetzt.'),
        ),
    ]
