# Generated by Django 5.1.5 on 2025-06-06 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_team_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('inviteid', models.AutoField(db_column='InviteID', primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('used', models.BooleanField(db_column='Used', default=False, help_text='Wird nach erfolgreicher Aktivierung auf True gesetzt.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('used_at', models.DateTimeField(blank=True, db_column='UsedAt', null=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='server.company')),
                ('created_by', models.ForeignKey(db_column='CreatedByUserID', on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'InviteToken',
                'managed': True,
            },
        ),
    ]
