# Generated by Django 5.1.5 on 2025-06-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(db_column='IsCompanyAdmin', default=False, help_text='True, wenn dieser User Administrator seiner Firma ist.'),
        ),
    ]
