# Generated by Django 5.1.5 on 2025-06-06 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_user_is_company_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('companyroleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=100, unique=True)),
                ('perm_invite_users', models.BooleanField(default=False)),
                ('perm_approve_requests', models.BooleanField(default=False)),
                ('perm_manage_settings', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CompanyRole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyUserRole',
            fields=[
                ('companyuserroleid', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='server.company')),
                ('companyrole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='server.companyrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CompanyUserRole',
                'managed': True,
                'unique_together': {('user', 'company')},
            },
        ),
    ]
