# Generated by Django 5.1.5 on 2025-06-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_companyrole_companyuserrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='perm_change_user_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyrole',
            name='perm_remove_users',
            field=models.BooleanField(default=False),
        ),
    ]
