# Generated by Django 5.1.5 on 2025-06-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_companyjoinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company_admin',
        ),
    ]
