# Generated by Django 5.1.5 on 2025-06-21 12:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_user_is_company_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companymail',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CompanyCreatedTimeStamp', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(db_column='CompanyIsVerified', default=False),
        ),
        migrations.CreateModel(
            name='CompanyDomain',
            fields=[
                ('domainid', models.AutoField(db_column='DomainID', primary_key=True, serialize=False)),
                ('domain', models.CharField(db_column='Domain', max_length=255, unique=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='server.company')),
            ],
            options={
                'db_table': 'CompanyDomain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyVerification',
            fields=[
                ('verificationid', models.AutoField(db_column='VerificationID', primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_column='VerificationToken', default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='VerificationCreated')),
                ('used', models.BooleanField(db_column='VerificationUsed', default=False)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='server.company')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CompanyVerification',
                'managed': True,
            },
        ),
    ]
